[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
kestrel = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
kestrel = "46PW8Yrw8KNtgLcmBEW9GQPjaYQJUxJSxM8KPBMJ5RMS"

[toolchain]
anchor_version = "0.31.0"